// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QNKPlWfjy503yq7c2AeMRN0f1d9hm5A',
    appId: '1:930535450860:web:4bc35094f8a6beec7d9dc9',
    messagingSenderId: '930535450860',
    projectId: 'poultry-guard',
    authDomain: 'poultry-guard.firebaseapp.com',
    storageBucket: 'poultry-guard.appspot.com',
    measurementId: 'G-W2DE6NBW5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQpyUgGYC4Zo_gGhDTv_gyIEowZUB7G4Q',
    appId: '1:930535450860:android:a9565b17b2c802e37d9dc9',
    messagingSenderId: '930535450860',
    projectId: 'poultry-guard',
    storageBucket: 'poultry-guard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgee85l_0iIpVuPNucufdMg58NHfhomSE',
    appId: '1:930535450860:ios:3fc9a4915ab6478c7d9dc9',
    messagingSenderId: '930535450860',
    projectId: 'poultry-guard',
    storageBucket: 'poultry-guard.appspot.com',
    iosBundleId: 'com.example.poultryguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgee85l_0iIpVuPNucufdMg58NHfhomSE',
    appId: '1:930535450860:ios:3fc9a4915ab6478c7d9dc9',
    messagingSenderId: '930535450860',
    projectId: 'poultry-guard',
    storageBucket: 'poultry-guard.appspot.com',
    iosBundleId: 'com.example.poultryguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4QNKPlWfjy503yq7c2AeMRN0f1d9hm5A',
    appId: '1:930535450860:web:b3f1dbeade0643bc7d9dc9',
    messagingSenderId: '930535450860',
    projectId: 'poultry-guard',
    authDomain: 'poultry-guard.firebaseapp.com',
    storageBucket: 'poultry-guard.appspot.com',
    measurementId: 'G-71NGG6WYY0',
  );
}
